### ISSUE TITLE
Add back button on the  package info. 

### ISSUE THREAD

**Issue by AmicoderDev** [awaisalwaisy/vuenpm#4]
**Issue Description:**

The package info page lacks a back button, making it challenging for users to navigate back. To enhance user experience, I suggest incorporating a back button. Additionally, please consider adding a route condition to confirm the user's origin route for better functionality.

**Suggested Solution:**

Place the back button at the top, following the search component. This location is optimal for easy accessibility.

**Comment by alwaisy** [comment]
Thanks for suggesting this feat. It is planned, visit readme.

**Comment by alwaisy** [comment]
@amicoder-lol It is fixed here https://github.com/awaisalwaisy/vuenpm/commit/364fff4aefe54f66f94b418a7d35165f6349e9fd
