### ISSUE TITLE
Website seems laggy

### ISSUE THREAD

**Issue by badasscodr** [awaisalwaisy/vuenpm#5]
**Issue Description:**

The website appears to be experiencing performance issues, and I suspect it may be related to the Quasar framework and potentially server-side rendering (SSR). The site seems slow in its response times, impacting the overall user experience.

**Comment by alwaisy** [comment]
Thanks for pointing out this issue. I am planning to go back to CSR or better to optimize the VPS. I am already using Cloudflare.
